name: environment variables
on: push
jobs:
  repo-name:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [ "${{ github.event.repository.name }}"]
    steps:
    - name: "Echo REpo name "
      run: echo $repo
